# Generated by Django 2.0.7 on 2018-09-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-mod_date'], 'verbose_name': '文档'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-mod_date'], 'verbose_name': '产品'},
        ),
    ]
